version: '3.3'

services:
  postgres_app:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/banxe_data_dev/
    env_file:
      - ./.env.dev
      
  django_app:
    build: 
      context: ./django_app
      dockerfile: Dockerfile.dev
    volumes:
      - ./django_app/:/home/django_app/
    ports:
      - 8005:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres_app

volumes:
  postgres_data: