# Generated by Django 4.0.3 on 2023-07-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('subaccount_id', models.CharField(max_length=50, verbose_name='subaccountID')),
                ('network', models.CharField(max_length=50, verbose_name='Network')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallet list',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=50, verbose_name='Recipient address')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_app.wallet', verbose_name='Service wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transaction list',
            },
        ),
    ]
