# Generated by Django 4.0.3 on 2023-07-09 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
