# Generated by Django 4.0.3 on 2023-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CANCELED', 'Canceled'), ('ACCEPTED', 'Accepted')], default='CREATED', max_length=50, verbose_name='Status'),
        ),
    ]
