# Generated by Django 4.0.3 on 2023-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0007_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CANCELED', 'Canceled'), ('APPROVED', 'Approved')], default='CREATED', max_length=50, verbose_name='Status'),
        ),
    ]
